In [2]:
import torch

In [3]:
t1 = torch.tensor(4.)

In [4]:
t1

tensor(4.)

In [5]:
t1.dtype

torch.float32

In [6]:
t2 = torch.tensor([1.,2.,3.,4.])

In [7]:
t2

tensor([1., 2., 3., 4.])

In [10]:
t4 = torch.tensor([[[11,12,13],[13,14,15]],[[15,16,17],[17,18,19]]])

#### 

In [11]:
t4

tensor([[[11, 12, 13],
         [13, 14, 15]],

        [[15, 16, 17],
         [17, 18, 19]]])

In [12]:
t2.shape()


TypeError: 'torch.Size' object is not callable

In [13]:
t2

tensor([1., 2., 3., 4.])

In [14]:
t2.size()

torch.Size([4])

In [15]:
t4.shape

torch.Size([2, 2, 3])

In [16]:
t2.shape

torch.Size([4])

In [20]:
x = torch.tensor(3.0)

In [21]:
w = torch.tensor(4.0
                 ,requires_grad=True)

In [22]:
b = torch.tensor(5.0, requires_grad =True)

In [23]:
y = w*x + b

In [24]:
y

tensor(17., grad_fn=<AddBackward0>)

In [25]:
y.backward()

In [26]:
y

tensor(17., grad_fn=<AddBackward0>)

In [27]:
x.grad

In [28]:
w.grad

tensor(3.)

In [29]:
b.grad

tensor(1.)